"""Primeira versao

Revision ID: 21f1aa098699
Revises: 
Create Date: 2026-05-31 07:37:00.723131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f1aa098699'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('serie', sa.String(length=20), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('turno', sa.Enum('manha', 'tarde', 'noite', name='turnos'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.DATE(), nullable=False),
    sa.Column('turma', sa.Integer(), nullable=True),
    sa.Column('nome_responsavel', sa.String(), nullable=False),
    sa.Column('celular_responsavel', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['turma'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=50), nullable=False),
    sa.Column('cargo', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('numero', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['cargo'], ['cargos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aluno', sa.Integer(), nullable=False),
    sa.Column('materia', sa.String(length=100), nullable=False),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('bimestre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notas')
    op.drop_table('logs')
    op.drop_table('usuarios')
    op.drop_table('alunos')
    op.drop_table('turmas')
    op.drop_table('cargos')
    # ### end Alembic commands ###
